### ISSUE TITLE
Recent youtube_dl python code seems to be broken

### ISSUE THREAD

**Issue by norbusan** [fossasia/susi_linux#522]
On Debian/buster DEsktop, as well as new Susibian image based on Buster, youtube fails:
```
Jun 26 02:35:29 raspberrypi python3[737]: ERROR: Signature extraction failed: Traceback (most recent call last):
Jun 26 02:35:29 raspberrypi python3[737]:   File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1232, in _decrypt_signature
Jun 26 02:35:29 raspberrypi python3[737]:     video_id, player_url, s
Jun 26 02:35:29 raspberrypi python3[737]:   File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1140, in _extract_signature_function
Jun 26 02:35:29 raspberrypi python3[737]:     res = self._parse_sig_js(code)
Jun 26 02:35:29 raspberrypi python3[737]:   File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1204, in _parse_sig_js
Jun 26 02:35:29 raspberrypi python3[737]:     jscode, 'Initial JS player signature function name', group='sig')
Jun 26 02:35:29 raspberrypi python3[737]:   File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 983, in _search_regex
Jun 26 02:35:29 raspberrypi python3[737]:     raise RegexNotFoundError('Unable to extract %s' % _name)
Jun 26 02:35:29 raspberrypi python3[737]: youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Jun 26 02:35:29 raspberrypi python3[737]:  (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Maybe this has something to do with youtube updates? Anyway @alok760 @stealthanthrax if you have time, please can you look into that?

**Comment by norbusan** [comment]
Ahh, youtube needs an update ... not only the player
https://github.com/ytdl-org/youtube-dl/issues/21484

**Comment by norbusan** [comment]
Closed by updating the requirements version in susi_linux
