### ISSUE TITLE
Gtk version error in Ubuntu 16.04

### ISSUE THREAD

**Issue by Muks14x** [fossasia/susi_linux#86]
On an install in ubuntu 16.04, on trying to run the app, I get a message telling me gtk+ 3.20 is needed. But app_window.py asks only for 3.0. It looks like the issue is because the .glade file generated is old, and expects 3.20. When I change the '3.20' in susi_app.glade to '3.0', the app runs fine.

**LogCat for the issue**

ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (MIXER,'IEC958 Playback Default',0,0,0): No such file or directory
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (MIXER,'IEC958 Playback Default',0,0,0): No such file or directory
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (MIXER,'IEC958 Playback Default',0,0,0): No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/muks/Stuff/susi_linux/main/states/susi_state_machine.py", line 90, in run
    self.current_state.on_enter(payload=None)
  File "/home/muks/Stuff/susi_linux/main/states/idle_state.py", line 32, in on_enter
    self.notify_renderer('idle')
  File "/home/muks/Stuff/susi_linux/main/states/base_state.py", line 51, in notify_renderer
    self.components.renderer.receive_message(message, payload)
  File "/home/muks/Stuff/susi_linux/main/ui/app_window.py", line 61, in receive_message
    self.state_stack.set_visible_child_name("mic_page")
AttributeError: 'SusiAppWindow' object has no attribute 'state_stack'

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/muks/Stuff/susi_linux/app.py", line 3, in <module>
    window = SusiAppWindow()
  File "/home/muks/Stuff/susi_linux/main/ui/app_window.py", line 23, in __init__
    builder.add_from_file(os.path.join(TOP_DIR, "glade_files/susi_app.glade"))
GLib.Error: gtk-builder-error-quark: /home/muks/Stuff/susi_linux/main/ui/glade_files/susi_app.glade:5:1 Required gtk+ version 3.20, current version is 3.18 (7)

I would like to work on this issue if possible, if this is an actual issue. 😊

**Comment by betterclever** [comment]
Yes. Please proceed. The required GTK+ version can be reduced to increase
support.
